// =====================================================
// Supabase Database 타입 정의
// 이 파일은 `supabase gen types typescript` 명령으로 자동 생성 가능
// =====================================================

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          business_number: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          logo_url: string | null;
          settings: Record<string, unknown>;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          business_number?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          settings?: Record<string, unknown>;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          business_number?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          settings?: Record<string, unknown>;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      employees: {
        Row: {
          id: string;
          business_id: string;
          employee_number: string | null;
          name: string;
          email: string | null;
          phone: string | null;
          department: string | null;
          position: string | null;
          hire_date: string | null;
          birth_date: string | null;
          hourly_rate: number;
          monthly_salary: number | null;
          salary_type: 'hourly' | 'monthly';
          contract: Record<string, unknown>;
          schedule: Record<string, unknown>[];
          privacy_consent: Record<string, unknown>;
          permissions: string[];
          is_active: boolean;
          inactive_reason: string | null;
          inactive_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_number?: string | null;
          name: string;
          email?: string | null;
          phone?: string | null;
          department?: string | null;
          position?: string | null;
          hire_date?: string | null;
          birth_date?: string | null;
          hourly_rate?: number;
          monthly_salary?: number | null;
          salary_type?: 'hourly' | 'monthly';
          contract?: Record<string, unknown>;
          schedule?: Record<string, unknown>[];
          privacy_consent?: Record<string, unknown>;
          permissions?: string[];
          is_active?: boolean;
          inactive_reason?: string | null;
          inactive_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          employee_number?: string | null;
          name?: string;
          email?: string | null;
          phone?: string | null;
          department?: string | null;
          position?: string | null;
          hire_date?: string | null;
          birth_date?: string | null;
          hourly_rate?: number;
          monthly_salary?: number | null;
          salary_type?: 'hourly' | 'monthly';
          contract?: Record<string, unknown>;
          schedule?: Record<string, unknown>[];
          privacy_consent?: Record<string, unknown>;
          permissions?: string[];
          is_active?: boolean;
          inactive_reason?: string | null;
          inactive_date?: string | null;
          updated_at?: string;
        };
      };
      employee_face_templates: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          embedding: number[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_id: string;
          embedding: number[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          employee_id?: string;
          embedding?: number[];
          updated_at?: string;
        };
      };
      employee_credentials: {
        Row: {
          id: string;
          employee_id: string;
          password_hash: string | null;
          registered_devices: string[];
          failed_login_count: number;
          locked_until: string | null;
          last_login_at: string | null;
          login_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          password_hash?: string | null;
          registered_devices?: string[];
          failed_login_count?: number;
          locked_until?: string | null;
          last_login_at?: string | null;
          login_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          password_hash?: string | null;
          registered_devices?: string[];
          failed_login_count?: number;
          locked_until?: string | null;
          last_login_at?: string | null;
          login_count?: number;
          updated_at?: string;
        };
      };
      attendance_records: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          date: string;
          check_in: string | null;
          check_out: string | null;
          check_in_at: string | null;
          check_out_at: string | null;
          total_break_minutes: number;
          break_start: string | null;
          break_end: string | null;
          work_location: string | null;
          notes: string | null;
          device_id: string | null;
          ip_address: string | null;
          check_in_method: 'face' | 'password' | 'emergency' | 'admin' | null;
          check_out_method: 'face' | 'password' | 'emergency' | 'admin' | null;
          status: 'active' | 'deleted' | 'modified';
          original_check_in: string | null;
          original_check_out: string | null;
          modified_by: string | null;
          modified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_id: string;
          date: string;
          check_in?: string | null;
          check_out?: string | null;
          check_in_at?: string | null;
          check_out_at?: string | null;
          total_break_minutes?: number;
          break_start?: string | null;
          break_end?: string | null;
          work_location?: string | null;
          notes?: string | null;
          device_id?: string | null;
          ip_address?: string | null;
          check_in_method?: 'face' | 'password' | 'emergency' | 'admin' | null;
          check_out_method?: 'face' | 'password' | 'emergency' | 'admin' | null;
          status?: 'active' | 'deleted' | 'modified';
          original_check_in?: string | null;
          original_check_out?: string | null;
          modified_by?: string | null;
          modified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          employee_id?: string;
          date?: string;
          check_in?: string | null;
          check_out?: string | null;
          check_in_at?: string | null;
          check_out_at?: string | null;
          total_break_minutes?: number;
          break_start?: string | null;
          break_end?: string | null;
          work_location?: string | null;
          notes?: string | null;
          device_id?: string | null;
          ip_address?: string | null;
          check_in_method?: 'face' | 'password' | 'emergency' | 'admin' | null;
          check_out_method?: 'face' | 'password' | 'emergency' | 'admin' | null;
          status?: 'active' | 'deleted' | 'modified';
          original_check_in?: string | null;
          original_check_out?: string | null;
          modified_by?: string | null;
          modified_at?: string | null;
          updated_at?: string;
        };
      };
      leaves: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          type: string;
          start_date: string;
          end_date: string;
          start_time: string | null;
          end_time: string | null;
          duration: number;
          unit: 'days' | 'hours';
          reason: string | null;
          status: 'pending' | 'approved' | 'rejected' | 'cancelled';
          requested_at: string;
          requested_by: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          attachments: string[];
          is_paid: boolean;
          deduct_from_salary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_id: string;
          type: string;
          start_date: string;
          end_date: string;
          start_time?: string | null;
          end_time?: string | null;
          duration?: number;
          unit?: 'days' | 'hours';
          reason?: string | null;
          status?: 'pending' | 'approved' | 'rejected' | 'cancelled';
          requested_at?: string;
          requested_by?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          attachments?: string[];
          is_paid?: boolean;
          deduct_from_salary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending' | 'approved' | 'rejected' | 'cancelled';
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          updated_at?: string;
        };
      };
      schedules: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          date: string;
          shift: 'morning' | 'afternoon' | 'night' | 'full' | 'off' | null;
          start_time: string | null;
          end_time: string | null;
          break_duration: number;
          location: string | null;
          notes: string | null;
          is_holiday: boolean;
          holiday_type: string | null;
          assigned_by: string | null;
          assigned_at: string;
          status: 'scheduled' | 'confirmed' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          employee_id: string;
          date: string;
          shift?: 'morning' | 'afternoon' | 'night' | 'full' | 'off' | null;
          start_time?: string | null;
          end_time?: string | null;
          break_duration?: number;
          location?: string | null;
          notes?: string | null;
          is_holiday?: boolean;
          holiday_type?: string | null;
          assigned_by?: string | null;
          assigned_at?: string;
          status?: 'scheduled' | 'confirmed' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          shift?: 'morning' | 'afternoon' | 'night' | 'full' | 'off' | null;
          start_time?: string | null;
          end_time?: string | null;
          break_duration?: number;
          location?: string | null;
          notes?: string | null;
          status?: 'scheduled' | 'confirmed' | 'cancelled';
          updated_at?: string;
        };
      };
      payroll_periods: {
        Row: {
          id: string;
          business_id: string;
          year: number;
          month: number;
          start_date: string;
          end_date: string;
          status: 'open' | 'processing' | 'closed';
          closed_at: string | null;
          closed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          year: number;
          month: number;
          start_date: string;
          end_date: string;
          status?: 'open' | 'processing' | 'closed';
          closed_at?: string | null;
          closed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'open' | 'processing' | 'closed';
          closed_at?: string | null;
          closed_by?: string | null;
          updated_at?: string;
        };
      };
      payroll_runs: {
        Row: {
          id: string;
          business_id: string;
          payroll_period_id: string;
          run_number: number;
          run_date: string;
          total_gross: number;
          total_deductions: number;
          total_net: number;
          employee_count: number;
          status: 'draft' | 'confirmed' | 'paid';
          confirmed_by: string | null;
          confirmed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          payroll_period_id: string;
          run_number?: number;
          run_date?: string;
          total_gross?: number;
          total_deductions?: number;
          total_net?: number;
          employee_count?: number;
          status?: 'draft' | 'confirmed' | 'paid';
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
        };
        Update: {
          total_gross?: number;
          total_deductions?: number;
          total_net?: number;
          employee_count?: number;
          status?: 'draft' | 'confirmed' | 'paid';
          confirmed_by?: string | null;
          confirmed_at?: string | null;
        };
      };
      payroll_lines: {
        Row: {
          id: string;
          business_id: string;
          payroll_run_id: string;
          payroll_period_id: string;
          employee_id: string;
          regular_hours: number;
          overtime_hours: number;
          night_hours: number;
          holiday_hours: number;
          total_hours: number;
          work_days: number;
          hourly_rate: number | null;
          base_pay: number;
          overtime_pay: number;
          night_pay: number;
          holiday_pay: number;
          bonus: number;
          incentive: number;
          transportation: number;
          meal_allowance: number;
          other_allowance: number;
          total_allowances: number;
          gross_pay: number;
          income_tax: number;
          local_tax: number;
          national_pension: number;
          health_insurance: number;
          long_term_care: number;
          employment_insurance: number;
          other_deduction: number;
          total_deductions: number;
          net_pay: number;
          status: 'draft' | 'confirmed' | 'paid';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          payroll_run_id: string;
          payroll_period_id: string;
          employee_id: string;
          regular_hours?: number;
          overtime_hours?: number;
          night_hours?: number;
          holiday_hours?: number;
          total_hours?: number;
          work_days?: number;
          hourly_rate?: number | null;
          base_pay?: number;
          overtime_pay?: number;
          night_pay?: number;
          holiday_pay?: number;
          bonus?: number;
          incentive?: number;
          transportation?: number;
          meal_allowance?: number;
          other_allowance?: number;
          total_allowances?: number;
          gross_pay?: number;
          income_tax?: number;
          local_tax?: number;
          national_pension?: number;
          health_insurance?: number;
          long_term_care?: number;
          employment_insurance?: number;
          other_deduction?: number;
          total_deductions?: number;
          net_pay?: number;
          status?: 'draft' | 'confirmed' | 'paid';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          bonus?: number;
          incentive?: number;
          transportation?: number;
          meal_allowance?: number;
          other_allowance?: number;
          other_deduction?: number;
          notes?: string | null;
          status?: 'draft' | 'confirmed' | 'paid';
          updated_at?: string;
        };
      };
      system_settings: {
        Row: {
          id: string;
          business_id: string;
          admin_password_hash: string | null;
          admin_fail_count: number;
          admin_locked_until: string | null;
          session_timeout_minutes: number;
          default_hourly_rate: number;
          overtime_rate: number;
          night_work_rate: number;
          holiday_work_rate: number;
          weekly_regular_hours: number;
          daily_regular_hours: number;
          standard_start_time: string;
          standard_end_time: string;
          night_work_start_time: string;
          night_work_end_time: string;
          lunch_break_start: string;
          lunch_break_duration: number;
          max_weekly_hours: number;
          max_overtime_hours: number;
          max_continuous_work_days: number;
          mandatory_break_after_hours: number;
          backup_enabled: boolean;
          backup_frequency: string;
          backup_time: string;
          backup_retention_days: number;
          notification_settings: Record<string, unknown>;
          face_match_threshold: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          admin_password_hash?: string | null;
          admin_fail_count?: number;
          admin_locked_until?: string | null;
          session_timeout_minutes?: number;
          default_hourly_rate?: number;
          overtime_rate?: number;
          night_work_rate?: number;
          holiday_work_rate?: number;
          weekly_regular_hours?: number;
          daily_regular_hours?: number;
          standard_start_time?: string;
          standard_end_time?: string;
          night_work_start_time?: string;
          night_work_end_time?: string;
          lunch_break_start?: string;
          lunch_break_duration?: number;
          max_weekly_hours?: number;
          max_overtime_hours?: number;
          max_continuous_work_days?: number;
          mandatory_break_after_hours?: number;
          backup_enabled?: boolean;
          backup_frequency?: string;
          backup_time?: string;
          backup_retention_days?: number;
          notification_settings?: Record<string, unknown>;
          face_match_threshold?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          admin_password_hash?: string | null;
          admin_fail_count?: number;
          admin_locked_until?: string | null;
          default_hourly_rate?: number;
          overtime_rate?: number;
          night_work_rate?: number;
          holiday_work_rate?: number;
          weekly_regular_hours?: number;
          daily_regular_hours?: number;
          standard_start_time?: string;
          standard_end_time?: string;
          night_work_start_time?: string;
          night_work_end_time?: string;
          lunch_break_start?: string;
          lunch_break_duration?: number;
          max_weekly_hours?: number;
          max_overtime_hours?: number;
          max_continuous_work_days?: number;
          mandatory_break_after_hours?: number;
          backup_enabled?: boolean;
          backup_frequency?: string;
          backup_time?: string;
          backup_retention_days?: number;
          notification_settings?: Record<string, unknown>;
          face_match_threshold?: number;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          business_id: string | null;
          timestamp: string;
          user_id: string | null;
          user_name: string | null;
          action: string;
          resource: string;
          resource_id: string | null;
          details: Record<string, unknown>;
          before_value: Record<string, unknown> | null;
          after_value: Record<string, unknown> | null;
          ip_address: string | null;
          user_agent: string | null;
          device_id: string | null;
          level: 'info' | 'warning' | 'error';
          success: boolean;
          error_message: string | null;
          duration_ms: number | null;
        };
        Insert: {
          id?: string;
          business_id?: string | null;
          timestamp?: string;
          user_id?: string | null;
          user_name?: string | null;
          action: string;
          resource: string;
          resource_id?: string | null;
          details?: Record<string, unknown>;
          before_value?: Record<string, unknown> | null;
          after_value?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_id?: string | null;
          level?: 'info' | 'warning' | 'error';
          success?: boolean;
          error_message?: string | null;
          duration_ms?: number | null;
        };
        Update: never;
      };
      notifications: {
        Row: {
          id: string;
          business_id: string;
          recipient_id: string | null;
          type: string;
          title: string;
          message: string;
          data: Record<string, unknown>;
          priority: 'low' | 'normal' | 'high' | 'urgent';
          status: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          channel: 'email' | 'sms' | 'push' | 'system';
          sent_at: string | null;
          read_at: string | null;
          expires_at: string | null;
          retry_count: number;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          recipient_id?: string | null;
          type: string;
          title: string;
          message: string;
          data?: Record<string, unknown>;
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          status?: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          channel?: 'email' | 'sms' | 'push' | 'system';
          sent_at?: string | null;
          read_at?: string | null;
          expires_at?: string | null;
          retry_count?: number;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          sent_at?: string | null;
          read_at?: string | null;
          retry_count?: number;
          error_message?: string | null;
          updated_at?: string;
        };
      };
    };
    Functions: {
      // Edge Functions는 여기에 정의
    };
  };
}
